//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE.EF.Model.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Irh_comp
    {
        public string Irh_Sys { get; set; }
        public string Irh_Prefix { get; set; }
        public string Irh_Comp1 { get; set; }
        public string Irh_connection { get; set; }
        public string Irh_inServer { get; set; }
    }
}
