//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE.EF.Model.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCR_mstr
    {
        public string Ocr_BatchID { get; set; }
        public string Ocr_PackinglistID { get; set; }
        public string Ocr_vend { get; set; }
        public string Ocr_doc_no { get; set; }
        public Nullable<System.DateTime> Ocr_rcp_date { get; set; }
        public string Ocr_lineID { get; set; }
        public string Ocr_ctnID { get; set; }
        public string Ocr_partno { get; set; }
        public string Ocr_po { get; set; }
        public string Ocr_custpart { get; set; }
        public string Ocr_qty { get; set; }
        public string Ocr_nw { get; set; }
        public string Ocr_gw { get; set; }
        public string Ocr_ref_no { get; set; }
        public string Ocr_ref_no1 { get; set; }
        public Nullable<int> Ocr_TTL { get; set; }
        public Nullable<decimal> Ocr_unitprice { get; set; }
        public string Ocr_status { get; set; }
        public Nullable<System.DateTime> Ocr_cre_date { get; set; }
        public string Ocr_cre_user { get; set; }
    }
}
