//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE.EF.Model.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_DET_Remote
    {
        public string PI_NO { get; set; }
        public int PI_LINE { get; set; }
        public string PI_CARTON_NO { get; set; }
        public string PI_SITE { get; set; }
        public string PI_PART { get; set; }
        public string PI_CO { get; set; }
        public string PI_DESC { get; set; }
        public Nullable<decimal> PI_QTY { get; set; }
        public string PI_LOT { get; set; }
        public Nullable<decimal> PI_NW { get; set; }
        public Nullable<decimal> PI_K200_NW { get; set; }
        public Nullable<decimal> PI_GW { get; set; }
        public string PI_SBU { get; set; }
        public string PI_REC_NO { get; set; }
        public Nullable<decimal> PI_PRICE { get; set; }
        public string PI_PALLET { get; set; }
        public Nullable<decimal> PI_PO_price { get; set; }
        public string PI_CONTRACT { get; set; }
        public Nullable<int> PI_SEQ { get; set; }
        public Nullable<int> PI_SEQ_CL { get; set; }
        public string PI_IQC { get; set; }
        public string PI_PO { get; set; }
        public string PI_Taxcode { get; set; }
        public string PI_ConnCode { get; set; }
        public string pi_user { get; set; }
        public Nullable<System.DateTime> pi_cre_time { get; set; }
        public Nullable<int> pi_ver { get; set; }
        public string pi_mfgr { get; set; }
        public string pi_mfgr_part { get; set; }
        public string pi_mfgr_name { get; set; }
        public string pi_Lic_req { get; set; }
        public Nullable<decimal> pi_ori_PO_price { get; set; }
        public string pi_PO_curr { get; set; }
        public Nullable<decimal> pi_curr_rate { get; set; }
        public Nullable<decimal> pi_us_rate { get; set; }
        public string pi_vend { get; set; }
    }
}
