//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_MSTR_Remote
    {
        public string PI_NO { get; set; }
        public Nullable<System.DateTime> PI_Date { get; set; }
        public string PI_Page { get; set; }
        public byte[] msrepl_synctran_ts { get; set; }
    }
}
