//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE.EF.Model.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class pi_sq
    {
        public string sq_type { get; set; }
        public int sq_id { get; set; }
        public string sq_name { get; set; }
        public string sq_desc { get; set; }
        public string sq_unit { get; set; }
        public string co_id { get; set; }
        public string co_desc { get; set; }
    }
}
