//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE.EF.Model.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class PIEEntities : DbContext
    {
        static string strconnect = @"metadata=res://*/PIE.csdl|res://*/PIE.ssdl|res://*/PIE.msl;provider=System.Data.SqlClient;provider connection string='data source=.;initial catalog=PIE;user id=sa;password=1234;MultipleActiveResultSets=True;App=EntityFramework'";
        public PIEEntities()
            : base(strconnect) //base("name=PIEEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Irh_comp> Irh_comp { get; set; }
        public virtual DbSet<pi_det> pi_det { get; set; }
        public virtual DbSet<PI_DET_Remote> PI_DET_Remote { get; set; }
        public virtual DbSet<pi_mstr> pi_mstr { get; set; }
        public virtual DbSet<PI_MSTR_Remote> PI_MSTR_Remote { get; set; }
        public virtual DbSet<pi_sq> pi_sq { get; set; }
        public virtual DbSet<pisr_grr> pisr_grr { get; set; }
        public virtual DbSet<pkey_ctl> pkey_ctl { get; set; }
        public virtual DbSet<plr_batch_mstr> plr_batch_mstr { get; set; }
        public virtual DbSet<plr_mstr> plr_mstr { get; set; }
        public virtual DbSet<plr_mstr_err> plr_mstr_err { get; set; }
        public virtual DbSet<plr_mstr_log> plr_mstr_log { get; set; }
        public virtual DbSet<plr_mstr_tran> plr_mstr_tran { get; set; }
        public virtual DbSet<sys_role> sys_role { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<sys_userInrole> sys_userInrole { get; set; }
        public virtual DbSet<ticketingPTMR> ticketingPTMR { get; set; }
        public virtual DbSet<OCR_mstr> OCR_mstr { get; set; }
        public virtual DbSet<vpi_detApisr_grr> vpi_detApisr_grr { get; set; }
        public virtual DbSet<vpi_report> vpi_report { get; set; }

        public virtual int sp_GenCtn_Tran(string batch_ID, Nullable<int> lineID, string plr_doc_type, string cartonID, string cartonType, string plr_po, Nullable<decimal> plr_qty, string ctnPre, Nullable<int> ctnFr, Nullable<int> ctnTo, string plr_cre_userid, string plr_user_ip, ObjectParameter result)
        {
            var batch_IDParameter = batch_ID != null ?
                new ObjectParameter("Batch_ID", batch_ID) :
                new ObjectParameter("Batch_ID", typeof(string));

            var lineIDParameter = lineID.HasValue ?
                new ObjectParameter("LineID", lineID) :
                new ObjectParameter("LineID", typeof(int));

            var plr_doc_typeParameter = plr_doc_type != null ?
                new ObjectParameter("plr_doc_type", plr_doc_type) :
                new ObjectParameter("plr_doc_type", typeof(string));

            var cartonIDParameter = cartonID != null ?
                new ObjectParameter("CartonID", cartonID) :
                new ObjectParameter("CartonID", typeof(string));

            var cartonTypeParameter = cartonType != null ?
                new ObjectParameter("CartonType", cartonType) :
                new ObjectParameter("CartonType", typeof(string));

            var plr_poParameter = plr_po != null ?
                new ObjectParameter("plr_po", plr_po) :
                new ObjectParameter("plr_po", typeof(string));

            var plr_qtyParameter = plr_qty.HasValue ?
                new ObjectParameter("plr_qty", plr_qty) :
                new ObjectParameter("plr_qty", typeof(decimal));

            var ctnPreParameter = ctnPre != null ?
                new ObjectParameter("ctnPre", ctnPre) :
                new ObjectParameter("ctnPre", typeof(string));

            var ctnFrParameter = ctnFr.HasValue ?
                new ObjectParameter("ctnFr", ctnFr) :
                new ObjectParameter("ctnFr", typeof(int));

            var ctnToParameter = ctnTo.HasValue ?
                new ObjectParameter("ctnTo", ctnTo) :
                new ObjectParameter("ctnTo", typeof(int));

            var plr_cre_useridParameter = plr_cre_userid != null ?
                new ObjectParameter("plr_cre_userid", plr_cre_userid) :
                new ObjectParameter("plr_cre_userid", typeof(string));

            var plr_user_ipParameter = plr_user_ip != null ?
                new ObjectParameter("plr_user_ip", plr_user_ip) :
                new ObjectParameter("plr_user_ip", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GenCtn_Tran", batch_IDParameter, lineIDParameter, plr_doc_typeParameter, cartonIDParameter, cartonTypeParameter, plr_poParameter, plr_qtyParameter, ctnPreParameter, ctnFrParameter, ctnToParameter, plr_cre_useridParameter, plr_user_ipParameter, result);
        }

        public virtual int sp_Get_WecCtnPre(string po_nbr, ObjectParameter wec_ctn_pre)
        {
            var po_nbrParameter = po_nbr != null ?
                new ObjectParameter("po_nbr", po_nbr) :
                new ObjectParameter("po_nbr", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Get_WecCtnPre", po_nbrParameter, wec_ctn_pre);
        }

        public virtual int sp_GetBatchID(ObjectParameter batchID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetBatchID", batchID);
        }

        public virtual int sp_GetPIID(ObjectParameter pIID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetPIID", pIID);
        }

        public virtual int sp_GetTID(ObjectParameter tID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetTID", tID);
        }
    }
}
