//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE.EF.Model.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisr_grr
    {
        public string pi_wec_ctn { get; set; }
        public int plr_LineID_tran { get; set; }
        public string Plant { get; set; }
        public string pisr_rir { get; set; }
        public string pisr_invoice { get; set; }
        public string pisr_part { get; set; }
        public string Pisr_receiver { get; set; }
        public string pisr_site { get; set; }
        public string pisr_po_nbr { get; set; }
        public Nullable<decimal> pisr_qty { get; set; }
        public string pisr_curr { get; set; }
        public Nullable<decimal> pisr_cost { get; set; }
        public Nullable<decimal> pisr_base_cost { get; set; }
        public Nullable<decimal> pisr_us_cost { get; set; }
        public string pisr_seq { get; set; }
        public string pisr_con_code { get; set; }
        public string pisr_ch_desc { get; set; }
        public Nullable<decimal> pisr_net_wt { get; set; }
        public string pisr_rec_type { get; set; }
        public string pisr_abc { get; set; }
        public string pisr_code { get; set; }
        public string pisr_lic_req { get; set; }
        public string pisr_sbu { get; set; }
        public string pisr_vend { get; set; }
        public string pisr_mfgr_name { get; set; }
        public string pisr_char01 { get; set; }
        public string pisr_char02 { get; set; }
        public string pisr_char03 { get; set; }
        public Nullable<decimal> pisr_dec01 { get; set; }
        public Nullable<decimal> pisr_dec02 { get; set; }
        public Nullable<int> pisr_int01 { get; set; }
        public Nullable<int> pisr_int02 { get; set; }
        public string pi_status { get; set; }
        public string pi_status_msg { get; set; }
        public string pi_remark { get; set; }
        public Nullable<System.DateTime> pi_cre_date { get; set; }
        public string pi_cre_userid { get; set; }
        public Nullable<System.DateTime> pi_update_date { get; set; }
        public string pi_edituser_id { get; set; }
        public string pi_user_ip { get; set; }
        public Nullable<short> pi_void_status { get; set; }
        public string pi_chr01 { get; set; }
        public string pi_chr02 { get; set; }
        public Nullable<int> pi_deci1 { get; set; }
        public Nullable<decimal> pi_deci2 { get; set; }
    }
}
