//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class plr_mstr
    {
        public plr_mstr()
        {
            this.plr_mstr_tran = new HashSet<plr_mstr_tran>();
        }
    
        public string Batch_ID { get; set; }
        public int LineID { get; set; }
        public string plr_status { get; set; }
        public string packingListID { get; set; }
        public string InvoiceID { get; set; }
        public string plr_pallet_no { get; set; }
        public string CartonType { get; set; }
        public string CartonID { get; set; }
        public string plr_po { get; set; }
        public string plr_co { get; set; }
        public string plr_partno { get; set; }
        public string plr_date_code { get; set; }
        public string plr_vend_mfgr { get; set; }
        public string Plr_vm_partno { get; set; }
        public Nullable<decimal> plr_carton_qty { get; set; }
        public Nullable<decimal> plr_qty { get; set; }
        public Nullable<System.DateTime> plr_rcp_date { get; set; }
        public Nullable<System.DateTime> plr_deli_date { get; set; }
        public string carton_id_prifix { get; set; }
        public Nullable<decimal> carton_id_from { get; set; }
        public Nullable<decimal> carton_id_to { get; set; }
        public string plr_doc_type { get; set; }
        public string re_mark { get; set; }
        public string plr_suppliers_id { get; set; }
        public string plr_site { get; set; }
        public Nullable<int> plr_ttl { get; set; }
        public string plr_um { get; set; }
        public string plr_nw { get; set; }
        public string plr_gw { get; set; }
        public string plr_um_w { get; set; }
        public Nullable<decimal> Plr_unitprice { get; set; }
        public string plr_msm { get; set; }
        public string plr_doc_no1 { get; set; }
        public Nullable<System.DateTime> plr_cre_date { get; set; }
        public string plr_cre_userid { get; set; }
        public Nullable<System.DateTime> plr_update_date { get; set; }
        public string plr_edituser_id { get; set; }
        public string plr_user_ip { get; set; }
        public Nullable<short> plr_void_status { get; set; }
        public string plr_chr01 { get; set; }
        public string plr_chr02 { get; set; }
        public Nullable<int> plr_deci1 { get; set; }
        public Nullable<decimal> plr_deci2 { get; set; }
    
        public virtual plr_batch_mstr plr_batch_mstr { get; set; }
        public virtual ICollection<plr_mstr_tran> plr_mstr_tran { get; set; }
    }
}
