//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE.EF.Model.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketingPTMR
    {
        public string t_id { get; set; }
        public string t_suppliers_id { get; set; }
        public Nullable<System.DateTime> t_inDocTime { get; set; }
        public Nullable<System.DateTime> t_backTime { get; set; }
        public string t_outWait { get; set; }
        public Nullable<System.DateTime> t_receTime { get; set; }
        public Nullable<System.DateTime> t_outAwayTime { get; set; }
        public Nullable<System.DateTime> t_waitTime { get; set; }
        public Nullable<System.DateTime> t_totalTime { get; set; }
        public Nullable<System.DateTime> t_time01 { get; set; }
        public Nullable<System.DateTime> t_time02 { get; set; }
        public Nullable<System.DateTime> t_cre_date { get; set; }
        public Nullable<System.DateTime> t_update_date { get; set; }
        public string t_cre_user { get; set; }
        public string t_user_ip { get; set; }
        public string t_chr01 { get; set; }
        public string t_chr02 { get; set; }
        public string t_chr03 { get; set; }
        public Nullable<decimal> t_dec01 { get; set; }
        public Nullable<decimal> t_dec02 { get; set; }
        public Nullable<int> t_int01 { get; set; }
        public Nullable<int> t_int02 { get; set; }
    }
}
