//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpi_detApisr_grr
    {
        public string PI_ID { get; set; }
        public int pi_LineID { get; set; }
        public string pi_wec_ctn { get; set; }
        public int plr_LineID_tran { get; set; }
        public Nullable<int> pi_pallet_no { get; set; }
        public string CartonNo { get; set; }
        public string CartonID { get; set; }
        public string pi_chr01 { get; set; }
        public string pisr_rir { get; set; }
        public string pisr_invoice { get; set; }
        public string pisr_part { get; set; }
        public string Pisr_receiver { get; set; }
        public string pisr_site { get; set; }
        public string pisr_po_nbr { get; set; }
        public Nullable<decimal> pisr_qty { get; set; }
        public string pisr_curr { get; set; }
        public Nullable<decimal> pisr_cost { get; set; }
        public Nullable<decimal> pisr_base_cost { get; set; }
        public Nullable<decimal> pisr_us_cost { get; set; }
        public string pisr_seq { get; set; }
        public string pisr_con_code { get; set; }
        public string sq_name { get; set; }
        public Nullable<decimal> pisr_net_wt { get; set; }
        public string pisr_rec_type { get; set; }
        public string pisr_abc { get; set; }
        public string pisr_code { get; set; }
        public string pisr_lic_req { get; set; }
        public string pisr_sbu { get; set; }
        public string pisr_vend { get; set; }
        public string pisr_mfgr_name { get; set; }
        public Nullable<decimal> pisr_dec01 { get; set; }
        public Nullable<decimal> pisr_dec02 { get; set; }
        public string pi_status { get; set; }
        public string Pallet_TTL_NW { get; set; }
        public Nullable<System.DateTime> pi_cre_date { get; set; }
    }
}
